version: msspi-{build}
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
clone_depth: 1
clone_folder: c:\github\deemru\msspi\
build_script:
- cmd: >-
    "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86

    cd build_windows

    make